import * as dotenv from 'dotenv';
import z from 'zod';

dotenv.config();

const envSchema = z.object({
	PORT: z.number().optional().default(9010),
	NODE_ENV: z.string().default('DEVELOPMENT'),

	FIREBASE_API_KEY: z.string(),
	FIREBASE_AUTH_DOMAIN: z.string(),
	FIREBASE_PROJECT_ID: z.string(),
	FIREBASE_STORAGE_BUCKET: z.string(),
	FIREBASE_MESSAGING_SENDER_ID: z.string(),
	FIREBASE_APP_ID: z.string(),

	FIREBASE_SERVICE_ACCOUNT_TYPE: z.string(),
	FIREBASE_SERVICE_ACCOUNT_PROJECT_ID: z.string(),
	FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID: z.string(),
	FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY: z.string(),
	FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL: z.string(),
	FIREBASE_SERVICE_ACCOUNT_CLIENT_ID: z.string(),
	FIREBASE_SERVICE_ACCOUNT_AUTH_URI: z.string(),
	FIREBASE_SERVICE_ACCOUNT_TOKEN_URI: z.string(),
	FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL: z.string(),
	FIREBASE_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL: z.string(),
	FIREBASE_SERVICE_ACCOUNT_UNIVERSE_DOMAIN: z.string(),
});

export const ENV = envSchema.parse({
	PORT: Number(process.env.PORT),
	NODE_ENV: process.env.NODE_ENV,

	FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
	FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
	FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
	FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
	FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
	FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,

	FIREBASE_SERVICE_ACCOUNT_TYPE: process.env.FIREBASE_SERVICE_ACCOUNT_TYPE,
	FIREBASE_SERVICE_ACCOUNT_PROJECT_ID:
		process.env.FIREBASE_SERVICE_ACCOUNT_PROJECT_ID,
	FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID:
		process.env.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID,
	FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY:
		process.env.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY,
	FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL:
		process.env.FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL,
	FIREBASE_SERVICE_ACCOUNT_CLIENT_ID:
		process.env.FIREBASE_SERVICE_ACCOUNT_CLIENT_ID,
	FIREBASE_SERVICE_ACCOUNT_AUTH_URI:
		process.env.FIREBASE_SERVICE_ACCOUNT_AUTH_URI,
	FIREBASE_SERVICE_ACCOUNT_TOKEN_URI:
		process.env.FIREBASE_SERVICE_ACCOUNT_TOKEN_URI,
	FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL:
		process.env.FIREBASE_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL,
	FIREBASE_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL:
		process.env.FIREBASE_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL,
	FIREBASE_SERVICE_ACCOUNT_UNIVERSE_DOMAIN:
		process.env.FIREBASE_SERVICE_ACCOUNT_UNIVERSE_DOMAIN,
});
